//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAN.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.CourseBranchMappings = new HashSet<CourseBranchMapping>();
        }
    
        public int Id { get; set; }
        public string BranchCode { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string HindiName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateTs { get; set; }
        public Nullable<System.DateTime> ModTs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseBranchMapping> CourseBranchMappings { get; set; }
    }
}
